[package]
name = "chain-cmp"
version = "0.2.0"
authors = ["isaacthefallenapple <isaacthefallenapple@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.38", features = ["full"] }
quote = "1.0.7"
proc-macro2 = "1.0.19"
